### ISSUE TITLE
conditional checkings

### ISSUE THREAD

**Issue by dhajoshi** [deanwilson/basic-puppet-integration-testing-docker-packer#1]
hello,

do you have any situation where you had to write some conditional statements and do testing in goss ? let say if my "region" is this my data should be "this" ?

Thanks,
DJ

**Comment by deanwilson** [comment]
Hi @dhajoshi,
Apologies for not spotting this issue earlier. I have not used goss in that way, plus my examples are no longer current so I'm unsure how you'd do those kind of checks now.
